image: 'restyled/restyler-black:v20.8b1'
command:
  - black
arguments: []
include:
  - '**/*.py'
interpreters:
  - python

enabled: true

exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*"

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

commit_template: |
  Restyled by ${restyler.name}
pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

labels: []

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - "*"
